version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/.env:/app/.env
      - ./frontend/package.json:/app/package.json
      # - ./frontend/node_modules:/app/node_modules
    command: npm run dev
    restart: always
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx-proxy
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx-proxy/nginx.conf
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
